### ISSUE TITLE
Find out what the hell the Activity Manager is

### ISSUE THREAD

**Issue by mattatobin** [binoc-central/comm-mailnews#7]
What even is this component and do we need it?

**Comment by wolfbeast** [comment]
It's record of all the activities that occurred in chronological order (either by timed function or by user interaction).
It's usefulness is debatable.
![image1](https://user-images.githubusercontent.com/3359132/45584489-8fcdb200-b8d4-11e8-8854-e048937a6fe9.png)

**Comment by mattatobin** [comment]
I like that the UI is lifted from the Toolkit Download Manager but yeah very debatable.
